/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Helley (https://sketchfab.com/Helley)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/terminal-8099551ab7c14a8097c6e0e4c3c423b7
Title: Terminal
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations, useTexture } from "@react-three/drei";

const DemoComputerV1 = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/terminal.glb");

  const txt = useTexture("/portfolio-texture.png");

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="08999dca7c814671bb73f89c6dc4fffffbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.015}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Box010" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Box010_Material_#29_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Box010_Material_#29_0"].geometry}
                    material={materials.Material_29}
                  />
                </group>
                <group
                  name="Box011"
                  position={[0, 91.073, 55.916]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <mesh
                    name="Box011_Material_#29_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Box011_Material_#29_0"].geometry}
                    material={materials.Material_29}
                  />
                </group>
                <group name="Object027" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Object027_Material_#29_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Object027_Material_#29_0"].geometry}
                    material={materials.Material_29}
                  />
                </group>
                <group
                  name="Cylinder036"
                  position={[0, 91.073, 38.156]}
                  rotation={[-Math.PI / 2, 0, 0]}
                >
                  <group name="Object_11" position={[13.524, 0, 0]}>
                    <mesh
                      name="Cylinder036_Material_#29_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Cylinder036_Material_#29_0"].geometry}
                      material={materials.Material_29}
                    />
                  </group>
                  <group name="Object028" position={[0, -17.76, 0]}>
                    <mesh
                      name="Object028_Material_#29_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Object028_Material_#29_0"].geometry}
                      material={materials.Material_29}
                    />
                    <group name="Object029" position={[0, 25.292, 3.695]}>
                      <group name="Object_16" position={[13.524, 0, 1.098]}>
                        <mesh
                          name="Object029_Material_#29_0"
                          castShadow
                          receiveShadow
                          geometry={nodes["Object029_Material_#29_0"].geometry}
                          material={materials.Material_29}
                        />
                      </group>
                      <group name="Dummy013">
                        <group
                          name="Cylinder037"
                          position={[0, 0.341, 0.199]}
                          rotation={[-0.89, 0, 0]}
                        >
                          <mesh
                            name="Cylinder037_Material_#29_0"
                            castShadow
                            receiveShadow
                            geometry={
                              nodes["Cylinder037_Material_#29_0"].geometry
                            }
                            material={materials.Material_29}
                          />
                        </group>
                      </group>
                      <group name="Object030" position={[0, 7.288, 5.825]}>
                        <group name="Object_22" position={[13.524, 0, 1.098]}>
                          <mesh
                            name="Object030_Material_#29_0"
                            castShadow
                            receiveShadow
                            geometry={
                              nodes["Object030_Material_#29_0"].geometry
                            }
                            material={materials.Material_29}
                          />
                        </group>
                        <group name="Dummy014" position={[2.441, 0, 0]}>
                          <group
                            name="Cylinder038"
                            position={[0.006, 0, 0]}
                            rotation={[0.593, -0.029, 0.02]}
                          >
                            <mesh
                              name="Cylinder038_Material_#29_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes["Cylinder038_Material_#29_0"].geometry
                              }
                              material={materials.Material_29}
                            />
                          </group>
                        </group>
                        <group name="Dummy015" />
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="Object031"
                  position={[0, 113.368, 33.508]}
                  rotation={[0, 0, -Math.PI]}
                >
                  <group name="Object_29" position={[0, -17.607, -3.897]}>
                    <mesh
                      name="Object031_Material_#29_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Object031_Material_#29_0"].geometry}
                      material={materials.Material_29}
                    />
                  </group>
                  <group
                    name="Cylinder040"
                    position={[0, -1.611, -3.021]}
                    rotation={[Math.PI / 2, 0, -Math.PI]}
                  >
                    <group name="Object_32" position={[13.524, 0, 0]}>
                      <mesh
                        name="Cylinder040_Material_#29_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["Cylinder040_Material_#29_0"].geometry}
                        material={materials.Material_29}
                      />
                    </group>
                    <group
                      name="Object032"
                      position={[0, 0, -1.098]}
                      rotation={[-Math.PI / 6, 0, 0]}
                    >
                      <group name="Object_35" position={[13.524, 0, 1.098]}>
                        <mesh
                          name="Object032_Material_#29_0"
                          castShadow
                          receiveShadow
                          geometry={nodes["Object032_Material_#29_0"].geometry}
                          material={materials.Material_29}
                        />
                      </group>
                      <group name="Dummy016" position={[-2.512, -1.38, 0]}>
                        <group
                          name="Cylinder041"
                          position={[0, 1.023, 0.182]}
                          rotation={[-2.203, 0, Math.PI]}
                        >
                          <mesh
                            name="Cylinder041_Material_#29_0"
                            castShadow
                            receiveShadow
                            geometry={
                              nodes["Cylinder041_Material_#29_0"].geometry
                            }
                            material={materials.Material_29}
                          />
                        </group>
                      </group>
                      <group name="Object033" position={[0, 6.476, -4.828]}>
                        <group name="Object_41" position={[13.524, 0, 1.098]}>
                          <mesh
                            name="Object033_Material_#29_0"
                            castShadow
                            receiveShadow
                            geometry={
                              nodes["Object033_Material_#29_0"].geometry
                            }
                            material={materials.Material_29}
                          />
                        </group>
                        <group name="Dummy017" position={[-2.512, 0, 0]} />
                        <group name="Dummy018" position={[2.239, 0, 0]}>
                          <group
                            name="Cylinder043"
                            position={[0.207, -0.006, 0.01]}
                            rotation={[-2.026, -0.001, -3.141]}
                          >
                            <mesh
                              name="Cylinder043_Material_#29_0"
                              castShadow
                              receiveShadow
                              geometry={
                                nodes["Cylinder043_Material_#29_0"].geometry
                              }
                              material={materials.Material_29}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="Object034" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Object034_Material_#29_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Object034_Material_#29_0"].geometry}
                    material={materials.Material_29}
                  />
                </group>
                <group name="Object035" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Object035_Material_#29_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Object035_Material_#29_0"].geometry}
                    material={materials.Material_29}
                  />
                </group>
                <group name="Object036" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Object036_Material_#29_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Object036_Material_#29_0"].geometry}
                    material={materials.Material_29}
                  />
                </group>
                <group
                  name="Cylinder044"
                  position={[16.617, 60.749, -19.653]}
                  rotation={[-Math.PI, 0, Math.PI / 2]}
                >
                  <group name="Object_54" position={[0, 0, 27.189]}>
                    <mesh
                      name="Cylinder044_Material_#29_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Cylinder044_Material_#29_0"].geometry}
                      material={materials.Material_29}
                    />
                  </group>
                </group>
                <group
                  name="Line008"
                  position={[16.617, 35.12, -45.33]}
                  rotation={[0, -1.571, 0]}
                >
                  <mesh
                    name="Line008_Material_#29_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Line008_Material_#29_0"].geometry}
                    material={materials.Material_29}
                  />
                </group>
                <group name="Object037" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Object037_Material_#29_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Object037_Material_#29_0"].geometry}
                    material={materials.Material_29}
                  />
                </group>
                <group
                  name="Cylinder052"
                  position={[0, 148.05, -18.789]}
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                >
                  <group name="Object_61" position={[0, 0, 27.189]}>
                    <mesh
                      name="Cylinder052_Material_#29_0"
                      castShadow
                      receiveShadow
                      geometry={nodes["Cylinder052_Material_#29_0"].geometry}
                      material={materials.Material_29}
                    />
                  </group>
                </group>
                <group name="Object038" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Object038_Material_#29_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Object038_Material_#29_0"].geometry}
                    material={materials.Material_29}
                  />
                </group>
                <group name="Box012" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Box012_Material_#29_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Box012_Material_#29_0"].geometry}
                    material={materials.Material_29}
                  />
                </group>
                <group name="Object039" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Object039_Material_#29_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Object039_Material_#29_0"].geometry}
                    material={materials.Material_29}
                  />
                </group>
                <group name="Object040" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh
                    name="Object040_Material_#29_0"
                    castShadow
                    receiveShadow
                    geometry={nodes["Object040_Material_#29_0"].geometry}
                    material={materials.Material_29}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/terminal.glb");

export default DemoComputerV1;
